{% set name = "libde265" %}
{% set version = "1.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/strukturag/libde265/releases/download/v{{ version }}/libde265-{{ version }}.tar.gz
  sha256: b921bc90521f28914bbf0c638c436b79831857ca4f7af1f3dd4ce2228bf40cfd

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libde265', max_pin='x.x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}
    - cmake
    - ninja

test:
  commands:
    - test -f $PREFIX/lib/libde265${SHLIB_EXT}      # [unix]
    - test -f $PREFIX/include/libde265/de265.h      # [unix]
    - test -f $PREFIX/lib/pkgconfig/libde265.pc      # [unix]
    - test -f $PREFIX/lib/cmake/libde265/libde265Config.cmake      # [unix]
    - if not exist %LIBRARY_LIB%\de265.lib exit 1       # [win]
    - if not exist %LIBRARY_BIN%\de265.dll exit 1       # [win]
    - if not exist %LIBRARY_INC%\libde265\de265.h exit 1       # [win]
    - if not exist %LIBRARY_LIB%\cmake\libde265\libde265Config.cmake exit 1       # [win]
    - dec265 -h

about:
  home: http://www.libde265.org/
  summary: Open h.265 video codec implementation
  description: |
    libde265 is an open source implementation of the h.265 video codec.
    It is written from scratch and has a plain C API to enable a simple
    integration into other software. libde265 supports WPP and tile-based
    multithreading and includes SSE optimizations. The decoder includes all
    features of the Main profile and correctly decodes almost all conformance
    streams.
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING
  dev_url: https://github.com/strukturag/libde265

extra:
  recipe-maintainers:
    - frmdstryr
